// @ts-nocheck
// eslint-disable-next-line @typescript-eslint/no-explicit-any
var Shamrock: any = (this as any).Shamrock || ((this as any).Shamrock = {});

Shamrock.BACKEND_SHEET_NAMES = {
  cadets: "Directory Backend",
  attendance: "Attendance Backend",
  events: "Events Backend",
  excusals: "Excusals Backend",
  adminActions: "Admin Actions",
  audit: "Audit Log",
  dataLegend: "Data Legend",
};

Shamrock.PUBLIC_SHEET_NAMES = {
  faqs: "FAQs",
  dashboard: "Dashboard",
  cadre: "Cadre & Leadership",
  directory: "Directory",
  attendance: "Attendance",
  events: "Events",
  excusals: "Excusals",
  audit: "Audit / Changelogs",
  dataLegend: "Data Legend",
};

Shamrock.CADET_FIELDS = [
  "last_name",
  "first_name",
  "as_year",
  "graduation_year",
  "flight",
  "squadron",
  "university",
  "cadet_email",
  "phone",
  "dorm",
  "home_town",
  "home_state",
  "dob",
  "cip_broad",
  "cip_code",
  "afsc",
  "flight_path_status",
  "status",
  "photo_url",
  "notes",
  "created_at",
  "updated_at",
];

Shamrock.EVENT_FIELDS = [
  "event_id",
  "event_name",
  "event_type",
  "training_week",
  "event_date",
  "event_status",
  "affects_attendance",
  "attendance_label",
  "expected_group",
  "flight_scope",
  "location",
  "notes",
  "created_at",
  "updated_at",
];

Shamrock.ATTENDANCE_FIELDS = [
  "cadet_email",
  "event_id",
  "attendance_code",
  "source",
  "updated_at",
];

Shamrock.EXCUSAL_FIELDS = [
  "excusal_id",
  "cadet_email",
  "event_id",
  "request_timestamp",
  "reason",
  "decision",
  "decision_by",
  "decision_timestamp",
  "attendance_effect",
  "source",
];

Shamrock.ADMIN_ACTION_FIELDS = [
  "action_id",
  "actor_email",
  "action_type",
  "payload_json",
  "created_at",
  "processed_at",
  "status",
];

Shamrock.AUDIT_FIELDS = [
  "audit_id",
  "timestamp",
  "actor_email",
  "actor_role",
  "action",
  "target_sheet",
  "target_table",
  "target_key",
  "target_range",
  "event_id",
  "request_id",
  "old_value",
  "new_value",
  "result",
  "reason",
  "notes",
  "source",
  "script_version",
  "run_id",
];

Shamrock.AUDIT_HEADERS_HUMAN = [
  "Audit ID",
  "Timestamp",
  "Actor Email",
  "Actor Role",
  "Action",
  "Target Sheet",
  "Target Table",
  "Target Key",
  "Target Range",
  "Event ID",
  "Request ID",
  "Old Value",
  "New Value",
  "Result",
  "Reason",
  "Notes",
  "Source",
  "Script Version",
  "Run ID",
];

Shamrock.ATTENDANCE_CODES = [
  "P",
  "E",
  "ES",
  "ER",
  "ED",
  "T",
  "U",
  "UR",
  "MU",
  "MRS",
  "N/A",
];

Shamrock.EVENT_STATUS = [
    "Draft", 
    "Published", 
    "Cancelled", 
    "Archived"
];

Shamrock.PROPERTY_KEYS = {
  frontendSpreadsheetId: "SHAMROCK_FRONTEND_SPREADSHEET_ID",
  backendSpreadsheetId: "SHAMROCK_BACKEND_SPREADSHEET_ID",
};

// Data legend option lists
Shamrock.DATA_LEGEND_OPTIONS = {
  as_year_options: ["AS100", "AS150", "AS200", "AS250", "AS300", "AS400", "AS500", "AS700", "AS800", "AS900"],
  flight_options: ["Alpha", "Bravo", "Charlie", "Delta", "Echo", "Foxtrot", "Abroad"],
  squadron_options: ["Blue", "Gold", "Abroad"],
  home_state_options: [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
  ],
  university_options: ["Notre Dame", "St. Mary's", "Holy Cross", "Trine", "Valparaiso"],
  dorm_options: [
    "Cross-Town",
    "Off-Campus",
    "Alumni Hall",
    "Baumer Hall",
    "Carroll Hall",
    "Coyle Community in Zahm Hall",
    "Dillon Hall",
    "Duncan Hall",
    "Dunne Hall",
    "Graham Family Hall",
    "Keenan Hall",
    "Keough Hall",
    "Knott Hall",
    "Morrissey Hall",
    "O'Neill Family Hall",
    "Siegfried Hall",
    "Sorin Hall",
    "Stanford Hall",
    "St. Edward's Hall",
    "Badin Hall",
    "Breen-Phillips Hall",
    "Cavanaugh Hall",
    "Farley Hall",
    "Flaherty Hall",
    "Howard Hall",
    "Johnson Family Hall",
    "Lewis Hall",
    "Lyons Hall",
    "McGlinn Hall",
    "Pasquerilla East Hall",
    "Pasquerilla West Hall",
    "Ryan Hall",
    "Walsh Hall",
    "Welsh Family Hall",
    "Undergraduate Community at Fischer",
    "Fischer Graduate Residences",
  ],
  afsc_options: [
    "Undecided",
    "Space Force",
    "11X - Pilot",
    "12X - Combat Systems Officer",
    "13A - Astronaut",
    "13B - Air Battle Manager",
    "13H - Aerospace Physiologist",
    "13M - Airfield Operations",
    "13N - Nuclear and Missile Operations",
    "13O - Multi-Domain Warfare Officer",
    "13S - Space Operations",
    "13Z - Rated Multi-Domain Warfare Officer",
    "14F - Information Operations",
    "14N - Intelligence",
    "15A - Operations Analysis Officer",
    "15W - Weather and Environmental Sciences",
    "16F - Foreign Area Officer (FAO)",
    "16G - Air Force Operations Staff Officer",
    "16K - Software Development Officer (SDO)",
    "16P - Political-Military Affairs Strategist (PAS)",
    "16R - Planning and Programming",
    "16Z - Rated Foreign Area Officer (FAO)",
    "17D - Warfighter Communications",
    "17S - Cyberspace Effects Operations",
    "17W - Warfighter Communications & IT Systems",
    "17Y - Cyber Effects & Warfare Operations",
    "18X - Remotely Piloted Aircraft (RPA) Pilot",
    "19G - Space Warfare Officer",
    "19Z - Special Warfare",
    "21A - Aircraft Maintenance",
    "21M - Munitions and Missile Maintenance",
    "21R - Logistics Readiness",
    "31P - Security Forces",
    "32E - Civil Engineer",
    "35B - Band",
    "35P - Public Affairs",
    "38F - Force Support",
    "41A - Healthcare Administrator",
    "42X - Biomedical Clinician",
    "43X - Biomedical Specialists",
    "44X - Physician",
    "46X - Nurse",
    "47X - Dental",
    "48X - Aerospace Medicine",
    "51J - Judge Advocate",
    "52R - Chaplain",
    "61C - Chemist/Nuclear Chemist",
    "61D - Physicist/Nuclear Engineer",
    "62E - Developmental Engineer",
    "62S - Materiel Leader",
    "63A - Acquisition Manager",
    "64P - Contracting",
    "65F - Financial Management",
    "65W - Cost Analysis",
    "71S - Special Investigations",
    "92F0 - Foreign Area Officer (FAO) Trainee",
    "92J0 - Non-designated Lawyer",
    "92J1 - AFROTC Educational Delay Law Student",
    "92J2 - Funded Legal Education Program Law Student",
    "92J3 - Excess Leave Law Student",
    "92M0 - HPSP Medical Student",
    "92M1 - USUHS Student",
    "92M2 - HPSP Biomedical Science Student",
    "92P0 - Physician Assistant Student",
    "92T0 - Pilot Trainee",
    "92T1 - Combat Systems Officer Trainee",
    "92T2 - Air Battle Manager Trainee",
    "92T3 - Remotely Piloted Aircraft Pilot Trainee",
  ],
  flight_path_status_options: ["Ready 4/4", "Active 3/4", "Enrolled 2/4", "Participating 1/4"],
  status_options: ["Active", "Leave", "Inactive", "Alumni"],
  cip_broad_options: [
    "01 - Agricultural/Animal/Plant/Veterinary Science and Related Fields",
    "03 - Natural Resources and Conservation",
    "04 - Architecture and Related Services",
    "05 - Area, Ethnic, Cultural, Gender, and Group Studies",
    "09 - Communication, Journalism, and Related Programs",
    "10 - Communications Technologies/Technicians and Support Services",
    "11 - Computer and Information Sciences and Support Services",
    "12 - Culinary, Entertainment, and Personal Services",
    "13 - Education",
    "14 - Engineering",
    "15 - Engineering/Engineering-Related Technologies/Technicians",
    "16 - Foreign Languages, Literatures, and Linguistics",
    "19 - Family and Consumer Sciences/Human Sciences",
    "21 - Reserved",
    "22 - Legal Professions and Studies",
    "23 - English Language and Literature/Letters",
    "24 - Liberal Arts and Sciences, General Studies and Humanities",
    "25 - Library Science",
    "26 - Biological and Biomedical Sciences",
    "27 - Mathematics and Statistics",
    "28 - Military Science, Leadership and Operational Art",
    "29 - Military Technologies and Applied Sciences",
    "30 - Multi/Interdisciplinary Studies",
    "31 - Parks, Recreation, Leisure, Fitness, and Kinesiology",
    "32 - Basic Skills and Developmental/Remedial Education",
    "33 - Citizenship Activities",
    "34 - Health-Related Knowledge and Skills",
    "35 - Interpersonal and Social Skills",
    "36 - Leisure and Recreational Activities",
    "37 - Personal Awareness and Self-Improvement",
    "38 - Philosophy and Religious Studies",
    "39 - Theology and Religious Vocations",
    "40 - Physical Sciences",
    "41 - Science Technologies/Technicians",
    "42 - Psychology",
    "43 - Homeland Security, Law Enforcement, Firefighting and Related Protective Services",
    "44 - Public Administration and Social Service Professions",
    "45 - Social Sciences",
    "46 - Construction Trades",
    "47 - Mechanic and Repair Technologies/Technicians",
    "48 - Precision Production",
    "49 - Transportation and Materials Moving",
    "50 - Visual and Performing Arts",
    "51 - Health Professions and Related Programs",
    "52 - Business, Management, Marketing, and Related Support Services",
    "53 - High School/Secondary Diplomas and Certificates",
    "54 - History",
    "55 - Reserved",
    "60 - Health Professions Residency/Fellowship Programs",
    "61 - Medical Residency/Fellowship Programs",
  ],
  cip_code_options: [
    "01.0000 - Agriculture, General",
    "03.0104 - Environmental Science",
    "04.0201 - Architecture",
    "05.0201 - African Studies",
    "09.0100 - Communication and Media Studies",
    "10.0201 - Photographic Technology/Technician",
    "11.0101 - Computer Science",
    "11.0701 - Computer Systems Networking and Telecommunications",
    "11.0802 - Data Modeling/Warehousing and Database Administration",
    "11.1003 - Computer and Information Systems Security/Information Assurance",
    "12.0503 - Culinary Arts/Chef Training",
    "13.1202 - Elementary Education and Teaching",
    "14.0101 - Engineering, General",
    "14.0701 - Chemical Engineering",
    "14.0901 - Computer Engineering, General",
    "14.1901 - Mechanical Engineering",
    "15.0613 - Manufacturing Engineering Technology/Technician",
    "16.0101 - Foreign Languages and Literatures, General",
    "19.0702 - Human Development, Family Studies, and Related Services",
    "22.0000 - Legal Studies, General",
    "23.0101 - English Language and Literature, General",
    "24.0101 - Liberal Arts and Sciences/Liberal Studies",
    "26.0101 - Biology/Biological Sciences, General",
    "27.0101 - Mathematics, General",
    "30.0000 - Multi-/Interdisciplinary Studies, General",
    "31.0505 - Kinesiology and Exercise Science",
    "38.0101 - Philosophy",
    "39.0602 - Theology/Theological Studies",
    "40.0501 - Chemistry, General",
    "41.0101 - Biology Technician/Biotechnology Laboratory Technician",
    "42.0101 - Psychology, General",
    "43.0104 - Criminal Justice/Safety Studies",
    "44.0401 - Public Administration",
    "45.0101 - Social Sciences, General",
    "46.0101 - Mason/Masonry",
    "47.0603 - Autobody/Collision and Repair Technology/Technician",
    "48.0508 - Welding Technology/Welder",
    "49.0101 - Air Transportation, General",
    "50.0101 - Visual and Performing Arts, General",
    "51.3801 - Registered Nursing/Registered Nurse",
    "52.0101 - Business/Commerce, General",
    "54.0101 - History, General",
  ],
};

// Cadet intake form headers
Shamrock.CADET_FORM_HEADERS = [
  "Timestamp",
  "Last Name",
  "First Name",
  "AS Year",
  "Graduation Year",
  "Flight",
  "Squadron",
  "University",
  "Dorm",
  "University Email",
  "Phone",
  "Home Town",
  "Home State",
  "DOB",
  "AFSC",
  "CIP Broad",
  "CIP Code",
  "Flight Path Status",
  "Status",
  "Photo Link",
  "Notes",
];

Shamrock.CADET_FORM_MACHINE_HEADERS = [
  "timestamp",
  "last_name",
  "first_name",
  "as_year",
  "graduation_year",
  "flight",
  "squadron",
  "university",
  "dorm",
  "cadet_email",
  "phone",
  "home_town",
  "home_state",
  "dob",
  "afsc",
  "cip_broad",
  "cip_code",
  "flight_path_status",
  "status",
  "photo_url",
  "notes",
];

// Public sheet header templates (machine/human)
Shamrock.PUBLIC_DIRECTORY_HEADERS = {
  machine: [
    "last_name",
    "first_name",
    "as_year",
    "graduation_year",
    "flight",
    "squadron",
    "university",
    "cadet_email",
    "phone",
    "dorm",
    "home_town",
    "home_state",
    "dob",
    "cip_broad",
    "cip_code",
    "afsc",
    "flight_path_status",
    "status",
    "photo_url",
    "notes",
    "updated_at",
    "source",
  ],
  human: [
    "Last Name",
    "First Name",
    "AS Year",
    "Class Year",
    "Flight",
    "Squadron",
    "University",
    "Email",
    "Phone",
    "Dorm",
    "Home Town",
    "Home State",
    "DOB",
    "CIP Broad Area",
    "CIP Code",
    "Desired / Assigned AFSC",
    "Flight Path Status",
    "Status",
    "Photo Link",
    "Notes",
    "Last Updated",
    "Source",
  ],
};

Shamrock.PUBLIC_ATTENDANCE_BASE_HEADERS = {
  machine: [
    "cadet_email", 
    "status", 
    "last_name", 
    "first_name", 
    "as_year", 
    "flight", 
    "squadron"],
  human: [
    "Email", 
    "Status", 
    "Last Name", 
    "First Name", 
    "AS Year", 
    "Flight", 
    "Squadron"],
};

Shamrock.PUBLIC_EVENTS_HEADERS = {
  machine: [
    "event_id",
    "term",
    "training_week",
    "event_type",
    "display_label",
    "attendance_label",
    "expected_group",
    "flight_scope",
    "status",
    "start_datetime",
    "end_datetime",
    "location",
    "notes",
    "created_at",
    "created_by",
  ],
  human: [
    "Event ID",
    "Term",
    "Training Week",
    "Event Type",
    "Display Name",
    "Attendance Column Label",
    "Expected Group",
    "Flight Scope",
    "Status",
    "Start Date/Time",
    "End Date/Time",
    "Location",
    "Notes",
    "Created At",
    "Created By",
  ],
};

Shamrock.PUBLIC_EXCUSALS_HEADERS = {
  machine: [
    "request_id",
    "event_id",
    "cadet_email",
    "cadet_last",
    "cadet_first",
    "cadet_flight",
    "cadet_squadron",
    "request_status",
    "decision",
    "decision_by",
    "decision_timestamp",
    "attendance_effect",
    "submitted_timestamp",
    "last_updated",
    "public_notes",
  ],
  human: [
    "Request ID",
    "Event",
    "Email",
    "Last Name",
    "First Name",
    "Flight",
    "Squadron",
    "Status",
    "Decision",
    "Decided By",
    "Decided At",
    "Attendance Effect",
    "Submitted",
    "Last Updated",
    "Notes",
  ],
};
