// Tab schemas and canonical header definitions used during setup.

namespace Schemas {
  // Minimal machine headers for key tables. Display headers default to machine headers if not provided.
  export const FRONTEND_TABS: Types.TabSchema[] = [
    { name: 'FAQs' },
    { name: 'Dashboard' },
    {
      name: 'Leadership',
      machineHeaders: [
        'last_name',
        'first_name',
        'rank',
        'role',
        'reports_to',
        'email',
        'cell_phone',
        'office_phone',
        'office_location',
      ],
      displayHeaders: [
        'Last Name',
        'First Name',
        'Rank',
        'Role',
        'Reports To',
        'Email',
        'Cell Phone',
        'Office Phone',
        'Office Location',
      ],
    },
    {
      name: 'Directory',
      machineHeaders: [
        'last_name',
        'first_name',
        'as_year',
        'flight',
        'squadron',
        'university',
        'email',
        'phone',
        'dorm',
        'cip_broad_area',
        'cip_code',
        'desired_assigned_afsc',
        'home_town',
        'home_state',
        'class_year',
        'dob',
        'flight_path_status',
        'photo_link',
        'notes',
      ],
      displayHeaders: [
        'Last Name',
        'First Name',
        'Year',
        'Flight',
        'Sqdn',
        'University',
        'Email',
        'Phone Number',
        'Dorm',
        'CIP Broad Area',
        'CIP',
        'Desired / Assigned AFSC',
        'Home Town',
        'Home State',
        'Class',
        'DOB',
        'Flight Path',
        'Photo Link',
        'Notes',
      ],
    },
    {
      name: 'Attendance',
      machineHeaders: [
        'last_name',
        'first_name',
        'as_year',
        'flight',
        'squadron',
        'overall_attendance_pct',
        'llab_attendance_pct',
      ],
      displayHeaders: [
        'Last Name',
        'First Name',
        'Year',
        'Flight',
        'Sqdn',
        'Overall',
        'LLAB',
      ],
    },
    {
      name: 'Data Legend',
      machineHeaders: [
        'as_year_options',
        'flight_options',
        'squadron_options',
        'university_options',
        'dorm_options',
        'home_state_options',
        'cip_broad_area_options',
        'afsc_options',
        'flight_path_status_options',
        'attendance_code_options',
      ],
      displayHeaders: [
        'AS Year Options',
        'Flight Options',
        'Squadron Options',
        'University Options',
        'Dorm Options',
        'Home State Options',
        'CIP Broad Area Options',
        'AFSC Options',
        'Flight Path Status Options',
        'Attendance Code Options',
      ],
    },
  ];

  export const BACKEND_TABS: Types.TabSchema[] = [
    {
      name: 'Directory Backend',
      machineHeaders: [
        'source',
        'last_name',
        'first_name',
        'as_year',
        'class_year',
        'flight',
        'squadron',
        'university',
        'email',
        'phone',
        'dorm',
        'home_town',
        'home_state',
        'dob',
        'cip_broad_area',
        'cip_code',
        'desired_assigned_afsc',
        'flight_path_status',
        'photo_link',
        'notes',
      ],
      displayHeaders: [
        'Source',
        'Last Name',
        'First Name',
        'Year',
        'Class',
        'Flight',
        'Sqdn',
        'University',
        'Email',
        'Phone Number',
        'Dorm',
        'CIP Broad Area',
        'CIP',
        'Desired / Assigned AFSC',
        'Home Town',
        'Home State',
        'DOB',
        'Flight Path',
        'Photo Link',
        'Notes',
      ],
    },
    {
      name: 'Leadership Backend',
      machineHeaders: [
        'last_name',
        'first_name',
        'rank',
        'role',
        'reports_to',
        'email',
        'cell_phone',
        'office_phone',
        'office_location',
      ],
      displayHeaders: [
        'Last Name',
        'First Name',
        'Rank',
        'Role',
        'Reports To',
        'Email',
        'Cell Phone',
        'Office Phone',
        'Office Location',
      ],
    },
    {
      name: 'Events Backend',
      machineHeaders: [
        'event_id',
        'term',
        'training_week',
        'event_type',
        'display_name',
        'attendance_column_label',
        'expected_group',
        'flight_scope',
        'status',
        'start_datetime',
        'end_datetime',
        'location',
        'notes',
        'created_at',
        'created_by',
      ],
      displayHeaders: [
        'Event ID',
        'Term',
        'Training Week',
        'Event Type',
        'Display Name',
        'Attendance Column Label',
        'Expected Group',
        'Flight Scope',
        'Status',
        'Start Datetime',
        'End Datetime',
        'Location',
        'Notes',
        'Created At',
        'Created By',
      ],
    },
    {
      name: 'Excusals Backend',
      machineHeaders: [
        'request_id',
        'event',
        'email',
        'last_name',
        'first_name',
        'flight',
        'squadron',
        'status',
        'decision',
        'decided_by',
        'decided_at',
        'attendance_effect',
        'submitted_at',
        'last_updated_at',
        'notes',
      ],
      displayHeaders: [
        'Request ID',
        'Event',
        'Email',
        'Last Name',
        'First Name',
        'Flight',
        'Squadron',
        'Status',
        'Decision',
        'Decided By',
        'Decided At',
        'Attendance Effect',
        'Submitted At',
        'Last Updated At',
        'Notes',
      ],
    },
    {
      name: 'Attendance Backend',
      machineHeaders: [
        'submission_id',
        'submitted_at',
        'event',
        'attendance_type',
        'email',
        'name',
        'flight',
        'cadets'
      ],
      displayHeaders: [
        'Submission ID',
        'Submitted At',
        'Event',
        'Attendance Type',
        'Email',
        'Name',
        'Flight',
        'Cadets'
      ],
    },
    {
      name: 'Audit Backend',
      machineHeaders: [
        'audit_id',
        'timestamp',
        'actor_email',
        'role',
        'action',
        'target_sheet',
        'target_table',
        'target_key',
        'target_range',
        'event_id',
        'request_id',
        'old_value',
        'new_value',
        'result',
        'reason',
        'notes',
        'source',
        'version',
        'run_id',
      ],
      displayHeaders: [
        'Audit ID',
        'Timestamp',
        'Actor Email',
        'Role',
        'Action',
        'Target Sheet',
        'Target Table',
        'Target Key',
        'Target Range',
        'Event ID',
        'Request ID',
        'Old Value',
        'New Value',
        'Result',
        'Reason',
        'Notes',
        'Source',
        'Version',
        'Run ID',
      ],
    },
    {
      name: 'Data Legend',
      machineHeaders: [
        'as_year_options',
        'flight_options',
        'squadron_options',
        'university_options',
        'dorm_options',
        'home_state_options',
        'cip_broad_area_options',
        'afsc_options',
        'flight_path_status_options',
        'attendance_code_options',
      ],
      displayHeaders: [
        'AS Year Options',
        'Flight Options',
        'Squadron Options',
        'University Options',
        'Dorm Options',
        'Home State Options',
        'CIP Broad Area Options',
        'AFSC Options',
        'Flight Path Status Options',
        'Attendance Code Options',
      ],
    },
  ];

  export const EXCUSALS_MANAGEMENT_SCHEMA: Types.TabSchema = {
    name: 'Excusals Management',
    machineHeaders: ['timestamp', 'decision', 'event', 'reason', 'email', 'last_name', 'first_name', 'flight', 'request_id'],
    displayHeaders: ['Timestamp', 'Decision', 'Event', 'Reason', 'Email', 'Last Name', 'First Name', 'Flight', 'Request ID'],
  };

  export function getTabSchema(name: string): Types.TabSchema | undefined {
    return FRONTEND_TABS.find((t) => t.name === name) || BACKEND_TABS.find((t) => t.name === name);
  }

  export function getHeaderIndex(tabName: string, header: string): number {
    const schema = getTabSchema(tabName);
    if (!schema?.machineHeaders) return -1;
    return schema.machineHeaders.indexOf(header);
  }
}
